kind: pipeline
name: default
type: docker
steps:
  - name: backend
    image: golang:alpine
    pull: true
    commands:
      - pwd
      - ls
      - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o app .
      - ./app