name: drone-demo

kind: pipeline
type: docker
workspace:
  base: /go
  path: src/github.com/cqasen/drone-demo

steps:
  - name: docker
    image: plugins/docker
    environment:
      GO111MODULE: on
      GOPROXY: https://mirrors.aliyun.com/goproxy/
    settings:
      repo: drone-demo
      auto_tag: true
      dockerfile: ./Dockerfile
    commands:
      - pwd
      - go env
      - go run app.go
