name: drone-demo
kind: pipeline
type: docker
#workspace:
#  base: /go
#  path: src/github.com/cqasen/drone-demo

steps:
  #  - name: build
  #    image: golang:alpine
  #    environment:
  #      GO111MODULE: on
  #      GOPROXY: https://mirrors.aliyun.com/goproxy/
  #    commands:
  #      - pwd
  #      - go env
  #      - go version
  #      - go mod download

  - name: docker
    image: plugins/docker
    pull: if-not-exists
    environment:
      app_env:
        from_secret: app_env
    settings:
      repo: cqasen/demo
      dockerfile: ./Dockerfile
      tags: latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  - name: deploy
    image: appleboy/drone-ssh
    pull: true
    settings:
      host: 111.229.103.26
      port: 22
      username: root
      password:
        from_secret: ssh_password
      script:
        - docker rmi -f cqasen/demo
        - docker login -u "$docker_username" -p "$docker_password"
        - docker pull cqasen/demo:latest
        - sh docker.sh run --name demo --replicas 1 --publish 8088:8080 --container cqasen/demo --tag latest
        - echo "run success"