name: drone-demo

kind: pipeline
type: docker
workspace:
  base: /go
  path: src/github.com/cqasen/drone-demo

steps:
  - name: build
    image: golang:alpine
    environment:
      GO111MODULE: on
      GOPROXY: https://mirrors.aliyun.com/goproxy/
    commands:
      - pwd
      - go env
      - go version

  - name: docker
    image: plugins/docker
    pull: true
    settings:
      repo: drone-demo
      auto_tag: true
      dockerfile: ./Dockerfile
      debug: true
      dry_run: true
    commands:
      - pwd
      - ls -al
      - docker -v
      - nohup dockerd &
      - docker build -t drone-demo:$${DRONE_TAG}  ./
    when:
      event: [ push, tag ]
      branch: master
    privileged: true
