kind: pipeline
name: drone

workspace:
  base: /srv/drone-demo
  path: .

steps:
  - name: build
    image: golang:alpine
    pull: true
    commands:
      - pwd
      - ls
      - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o app .
      - ./app