name: drone-demo
kind: pipeline
type: docker
workspace:
  base: /go
  path: src/github.com/cqasen/drone-demo

steps:
  - name: build
    image: golang:alpine
    environment:
      GO111MODULE: on
      GOPROXY: https://mirrors.aliyun.com/goproxy/
    commands:
      - pwd
      - go env
      - go version
      - go mod download

  - name: publish
    image: plugins/docker
    volumes:
      - name: docker         # 挂载下面定义的Volumn
        path: /var/run/docker.sock   # 与宿主机用同一docker
    settings:
      repo: cqasen/demo
      dockerfile: ./Dockerfile
      tags: latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  - name: deploy
    image: appleboy/drone-ssh
    pull: true
    settings:
      host: 111.229.103.26
      port: 22
      username: root
      password:
        from_secret: ssh_password
      script:
        - docker rmi -f cqasen/demo
        - docker login -u ${{docker_username}} -p ${{docker_password}}
        - echo "login docker"
        - echo "login success, pulling..."
        - docker pull cqasen/demo:latest
        - echo "image running"
        - docker run -p 8088:8088 -d cqasen/demo:latest
        - echo "run success"