name: drone-demo
kind: pipeline
type: docker
#workspace:
#  base: /go
#  path: src/github.com/cqasen/drone-demo
steps:
  #  - name: build
  #    image: golang:alpine
  #    environment:
  #      GO111MODULE: on
  #      GOPROXY: https://mirrors.aliyun.com/goproxy/
  #    commands:
  #      - pwd
  #      - go env
  #      - go version
  #      - go mod download

  - name: docker
    image: plugins/docker
    pull: if-not-exists
    environment:
      app_env:
        from_secret: app_env
    settings:
      repo: cqasen/demo
      dockerfile: ./Dockerfile
      tags: latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password


  - name: deploy
    image: appleboy/drone-ssh
    pull: if-not-exists
    settings:
      host:
        from_secret: host_proc_1
        port:
          from_secret: port_proc_1
        username:
          from_secret: ssh_username
        password:
          from_secret: ssh_password
      script:
        - echo ${DRONE_REPO_NAME}
        - docker rmi -f cqasen/demo
        - docker login -u "$docker_username" -p "$docker_password"
        - docker pull cqasen/demo:latest
        - docker service create --name demo --replicas 1 -t --publish 8088:8088 cqasen/demo:latest
        - echo "run success"