version: "3"
services:
  gin-demo:
    image: cqasen/demo:latest
    ports:
      - 8088:8088
    environment:
      ENVIRONMENT: local
    volumes:
      - /wwwlogs:/wwwlogs

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8088"] # 设置检测程序
      interval: 1m30s # 设置检测间隔
      timeout: 10s # 设置检测超时时间
      retries: 3 # 设置重试次数
      start_period: 40s # 启动后，多少秒开始启动检测程序