# Primary
SYSTEM_NAME: drone-demo
LOG_LEVEL: debug
LOG_PATH: /wwwlogs/
HTTP_PORT: 8088
# ES
ELASTICSEARCH_URL: http://111.229.103.26:9200/
ELASTICSEARCH_USERNAME: elastic
ELASTICSEARCH_PASSWORD: 123456
ELASTICSEARCH_SNIFF: false
# Redis
REDIS_AUTO_CONNECT: true
REDIS_HOST: 192.168.0.222
REDIS_PORT: 6379
REDIS_USER:
REDIS_AUTH: