# Primary
SYSTEM_NAME: drone-demo
LOG_LEVEL: debug
LOG_PATH: /wwwlogs/
HTTP_PORT: 8088
# ES
ELASTICSEARCH_URL: http://127.0.0.1:9200/
ELASTICSEARCH_USERNAME: elastic
ELASTICSEARCH_PASSWORD: 123456
ELASTICSEARCH_SNIFF: false