# Primary
SYSTEM_NAME: drone-demo
LOG_LEVEL: debug
LOG_PATH: /wwwlogs/
HTTP_PORT: 8088
# ES
ELASTICSEARCH_URL: http://111.229.103.26:9200/
ELASTICSEARCH_USERNAME: elastic
ELASTICSEARCH_PASSWORD: 123456
ELASTICSEARCH_SNIFF: false
# Redis
REDIS_AUTO_CONNECT: false
REDIS_HOST: 192.168.0.222
REDIS_PORT: 6379
REDIS_USER:
REDIS_AUTH:

#mysql
MYSQL_AUTO_CONNECT: true
MYSQL_DATABASE: zblog
MYSQL_MASTER_HOST: 111.229.103.26
MYSQL_MASTER_PORT: 13306
MYSQL_MASTER_USER: root
MYSQL_MASTER_PASS: cqasen@qq.com