name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: pwd1
        run: pwd

      - name: ls
        run: ls -al

      - name: Login to docker hub
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build :latest
        if: success()
        run: docker build -t cqasen/demo:latest .

      - name: pwd2
        run: pwd

      - name: ls2
        run: ls -al

      - name: Push to docker hub :latest
        uses: actions-hub/docker@master
        if: success()
        with:
          args: push cqasen/demo:latest
